### ISSUE TITLE
Integration with Whatapp

### ISSUE THREAD

**Issue by jonasbrant** [exoplatform/chat-application#610]
the possibility to integrate and forward messages from whatapp to exo chat could be a great oportunity to stimulate exo chat use. 
we usualy recieve messagens in whatapp and because it is not easy to foward we tend to comunicate using whatapp

**Comment by Jihed525** [comment]
Hi @jonasbrant 

a very precious add-on to eXo Platform if implemented indeed.

Yet, could you use the following link to make sure your suggestions to be considered eXo Product Team : [eXo Community Q&A](https://github.com/exoplatform/exo-community/discussions/categories/q-a) 

Best,

**Comment by jonasbrant** [comment]
THank you @Jihed525 i include where you sugested
