### ISSUE TITLE
Authentication mechanism conflict with MongoDB 3.2.0

### ISSUE THREAD

**Issue by jjakob** [exoplatform/chat-application#74]
When connecting to MongoDB with authentication enabled, Mongo throws an error, e.g.: 
`Failed to authenticate chatsvc@chat with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document`

As described [here](https://docs.mongodb.org/manual/core/authentication/), MongoDB default authentication mechanism is 5 (SCRAM-SHA-1) but Chat application is connecting with mechanism 3 (MONGODB-CR). To use this mechanism in MongoDB it is required to delete all users, change auth. mechanism from 5 to 3 and recreate the users.
This requirement is not mentioned anywhere in the documentation, nor is any restriction as to what version of MongoDB is required.
If the issue is the mongo java driver version 2.12.2, perhaps updating that to version 3.2 would be nice as that supports MongoDB versions 2.4 through 3.2. Or it's just a default authentication mechanism setting that requires to be changed. I'm not acquainted with how this driver/code works so this is a bit of speculation on my part.

**Comment by trangvh** [comment]
@jjakob Thank you for reporting this issue. The mongo driver has been upgraded to 2.14.0 at commit f930fe4 .

The upgrade to mongo driver 3.2 will be handled later at https://jira.exoplatform.org/browse/CHAT-345.
