### ISSUE TITLE
missing index ?

### ISSUE THREAD

**Issue by gpicavet** [exoplatform/chat-application#87]
Hello,

I'm doing some load testing with 100 000 rooms and 7 500 000 messages (timestamp of messages are within the last 30 days).

query profile show that some read requests scan all the messages collection, because timestamp criteria is not selective enough.

When i add an index on roomId field, all is getting faster

**Comment by thomasdelhomenie** [comment]
I create a Jira for your feedback : https://jira.exoplatform.org/browse/CHAT-388. Feel free to comment.
Thanks !

**Comment by thomasdelhomenie** [comment]
@grisha78  I added a PR to fix this issue : https://github.com/exo-addons/chat-application/pull/36
Feel free to comment if necessary.

**Comment by gpicavet** [comment]
The compound index performs better than single roomId like i did.
My throughput has just grown by 20% !
Thanks

**Comment by thomasdelhomenie** [comment]
Good to hear :)
The changes have been merged to the develop branch. This branch contains a bunch of improvements and is still compatible with Platform 4.3.0 (this is the version used in community.exoplatform.org).
Thanks again for your feedback !
